/**
 * Made-up files for `check.ts`, generated by Python's own `plistlib` so the
 * reader is tested against an implementation that is not its own.
 *
 * Invented from end to end — series called "Test Series" read on sites that
 * happen to exist. A real backup is somebody's reading history, and none of it
 * belongs in a public repository, whatever it would prove.
 *
 * `BACKUP` is a zip laid out as iMazing lays out an app backup: favourites and
 * history as `NSKeyedArchiver` graphs of `ComicBookItem`s under
 * `Container/Documents`, with other files beside them that must be ignored.
 * `PLAIN` is an ordinary binary plist holding one of every type the reader
 * understands.
 */
export const BACKUP = [
  'UEsDBBQAAAAIANohO108dkuGigMAAD4EAAAiAAAAQ29udGFpbmVyL0RvY3VtZW50cy9jb21pY0Jvb2tzLmRhdF2STWwbVRDH',
  '35vNl504XsdJkzSt48Su24TWX03atHzVddwSQpzGa8d2Emf7vPsab7zeNbubkPT0EBJqJQQSF05IUYt6AVEEQgiBOICEIoEE',
  'WMABekAIqRI3jgVVIK8DQp3LfLyZn2b+euW6qphWNPo9Bq6tveN5qxgkhlRRtqlRCOrlTSpZZjZo6fVCcJsapqJrIu9OC/N0',
  'l8qJg8a7fKizq7fv0PDhkSNHx0PHH3/iyaeeToSS888tLKSvhDKra6XS+tVQeTMX1LZUteFwdvcUgpJKTJOaK61AIzV6q8dV',
  'Suo1Rbqo69U5i9YKaWHRXqHhcLr527zHtZ4WFrYsUlZpwjDIbj4t2L7hcHr7b/cPuNb+exeolUsLAm3ODg7dGnItp4VZYtHV',
  'LDUtv0ANhZprNaJtkCqpElW3MrH40umGb9Q/ttxaaSUthA8UYNxewxcIHsunhbCl1ChrCyT2A9d/QQiJ/FjFsurm+UiE7pBa',
  'XaVhRdsmqiJHJH2bGuHN+sZPvhMTk4+dPBWORGPx01PTZ87OnDtfkpqnJps9OUMt2lma1KjIe+w4QyWqWbm6TCwq8t6qrUxT',
  'lTlzUbusK9rGqkGJTOVkRaCWyHsMKumGnKyQukWNJmmlVblCNqjI860kY480hci/QMumYlGGWTdrZ50O5mBdPGJO1rGWTQlZ',
  'v5DKzKWEsSyxzK1MLLYUb4pzwRbiYiCx7+7eQwj9/7TZ1KXpy8/MzD3LvMzF3MzDeNbHekWeX1Rl/yVFU8wKlf2LGi3awteJ',
  'Uc1MR5vYRRu7FEh8/mDy6iNYIZtbzhdmiitshA2wwS42zIbYYXYon1KpRKlcsGHX9B1hKnauCRNtGAkk9qPY/whMkun0tY2Z',
  'isIC7CgbZWPMz8aZr+EbraoM3qppep31sH52hAW/M8x16d/vaIrzdJcd60P45T3UhTxoBAXRBIqjWVRDJtpBL6JX0GvoTXQH',
  'vY3uos/Ql+gr9A26h35F99Hv6A/0EDuxC7txPx7BIXwCT+AwPoNncAJTfB3fwK/jO/hTvI/v4fv4TwBogw7oAid0gwvc4AEv',
  'DMA4HIdJOAkxiMNZuAA5yEMRVqEEIhCQYBsYvAQ34Ca8Cm/AO/AuvAfvwwfwIXwEH8Mn8AV8Dd/CD/Aj/Ay/wQP4Cx7C3xzm',
  'OK6d6+R6uF7Oyw1wg9wwN8L5uFNcBNkGuOXR1oE/MG7qH1BLAwQUAAAACADaITtdbARgiwIHAAASCQAAJAAAAENvbnRhaW5l',
  'ci9Eb2N1bWVudHMvY29taWNIaXN0cm95LmRhdH2Ue3gU1RnG35k5Z7jDclG5RQIbRG7Znd3JDUhwCZsQAxv2TEIuEJbJ7iFZ',
  'spewOwkgVT5bi9bWFlGpWlAuBbWU0lJpLbUUpQjUegGlVdoq2lZrbbG29YLa2icJ2//K+ec7Z57v/d75ft95TltXIp51vN6X',
  'oUCFBgYOHf9RlOYCOxPtiPfITFNBum2NjDrZ+gIn3dVU0CMz2Xg6FXGNCFm1coOMBS4nHnQ5GICBGI5RuBrjMB4TMBF5uBaT',
  'kI+JmIyZ8MCLcViIIKpQhWrcCA8WowHL0Ihr+3KbsAIerEQ7OhBH/LJ+DarQiQSSSCGNRkxAEF1YiwyycNCNHqzDemzATdiI',
  'L+Bm3IJNINyKL+JLuA1fxmbcjjvwFdyJr+JruAtfxzewBXdjK+5BHPfiFDz4JV7CyziHc/g1foNzeAW/hwev422MRwp5yMOf',
  '8S48+Bs+aChIdScSZzEIgzEEQ5sKogk7m5XZlv5Nyk7K3RiKYa2V6WQ8uiCd7qxxZLIpZNX1oewXjoBrD1wYiWErQ9aSbsdu',
  'S8hAJmNvaAxZfbE/bTTG7MEYXIVhK/6XZkmnIWRZ8nKlazB2N8Zi2LKQtdB25PJ6mXXyLZmJy+yKpJ1qtzvtTjuRdoThs8zZ',
  'RtgI+8L+ZaG0E4/Ks5gCNwowdVn/v7eErMLLAydtL67DNFyP6ZhBg2gwDaGhNKxXMQuzUdgYsgqdeFIScwdOuW+6ACDimtzh',
  'OF3ZOR6PXG8nuxKyMJ7qsRPxmCea7pGZwjVd7ecxBQZ88MNEEYpRglKUYQ7mYh7KUYH5uAEBLEBla7SXXmWvriGTaO47heyk',
  'jLhG9u2FjMqU09AVsx0ZcY3u7IPdC7omW5eqTsdT7csz0o7JWGWHJZ2Ia2RGRtOZWGWH3eXITG+llv4vS+12GXG5+g+iT9LL',
  'sXGdbMvGHUkKuYjTgEE0nAa6BtAI0pv7sK6OZ6Qw/OGiHMRFu1BDV+cA1boDp6bHdwL4fy0vQQh1qMBShCFgoZ7G0SgaQ9fQ',
  'VS6VxtLoFfVBqz7fCoqaoDW53nay3cIwcm7Nu9GC5TSJ8nOOre7AqRFDruQYwSrYqEAboohBYjW5aQLl0WS61gWaQhMjLldd',
  'IpZfFU/Fsx0yll+Xkv3NdtmZTlHkDZvh4nBJuDRcJgyvMExhFAmjWBglwigVRpnweYXPED6f8PmFzxS+IuErFr4S4SsVvjLh',
  '9wq/Ifw+4fcLvyn8RcJfLPwlwl8q/GXC9ArTEKZPmH5hmsIsEmaxMEuEWSrMslzX9x10+bAN38T9eAAP4lvYjh14CA9jJ3Zh',
  'N/bg29iLfXgEj+IxfAf78V0cwPdwEN/HD3AIP8TjOIwf4cd4Aj/BEfwUT+JnOIqf4xiewtM4jl/gBJ7BSZpOM2gmzaLZVEge',
  '8pJBPvKTSUVUTCVUSmU0h+bSPCqnCppPN1CAFlAlLaQgVVE1LaIaupFqaTEtoRDV0VIKkyCL6qmBllEjNVEzteTmdtodePrS',
  'jFVXmNuz+BWew/N4AS8ihjM4S600laYNpOV0Pa2g6xqDCRmVMtbUfzHT6y3TKLNMo8QyjdIculf34Dx+i99RlGIkc+avuQOn',
  'vEr+Fcwv4A28iQr8AX9EDH/CW9RBEbJpNbVRO62KuFwh2SMz+VV2T7o7E3dkLOf4zi78hVI5p7+6A89sPXThCk4X8R7+jgq8',
  'j38ghn/iX7SW1lCC0pSkLursL/shPiJ1Hz7GJXyCT/EZ/k0jaTwV0EqKU+YMPlewMpp7eLORWrmBsqOgbN6JgRgHN2bBwBws',
  'VkqUcqVKqVNalIiSVHqUTcpm5T5lh7JPOaAcUY4pp5XnlXPKG8pF5X3lA+Uj5ZLyqaqqQ9RRap46SZ2hzlILVa/qU021XA2q',
  '1epS1VF3qPvVw+pp9XX1XfVzbbCWp03VpmnTtZnabK1Q82o+zdSKtVJtgRbUqrWlmqU1aCu1dm2LtlW7V9um3a89qG3XHtJ2',
  'age0Q9ph7ah2XDuhndRe1F5lKmNMZwPZYDaUDWcuNopNZR7mYyYrZqVsDpvH5rMFLMgWsVoWYmFWzxpZC2tlq1iUrWZxlmBp',
  'lmHdbD3byG5ht7Lb2O3sTnYX28LuYdvYA2w7e5jtZnvZo2w/e5xP4Hl8Ep/M3Xwqn8an85l8Nvdwg/t5ES/hZXwuL+fzeYBX',
  '8iCv5jW8li/hdTzMLd7AG3kzX85beYTbPMolb+dx3smTPM3X8izv5uv4Br6R38w38Tv43fwIf5If5cf4U/w4P8FP8tP8DD/P',
  'X+Nv8rf4e/xD/jH/hH+mc324XqKX6XP1cn2+HtAr9aDepNt6TF+tp/X1+i59j75Xf0R/TN+vH9AP6k/oR/ST+mn9Wf05/QX9',
  'jP6S/or+tv4O+paq9kflcswt/eJ/AVBLAwQUAAAACADaITtdRK/cNQoAAAAIAAAALwAAAENvbnRhaW5lci9MaWJyYXJ5L1By',
  'ZWZlcmVuY2VzL2NvbS5leGFtcGxlLnBsaXN0y8svUShKTUwBAFBLAwQUAAAACADaITtdRK/cNQoAAAAIAAAAFAAAAGlUdW5l',
  'c01ldGFkYXRhLnBsaXN0y8svUShKTUwBAFBLAQIUABQAAAAIANohO108dkuGigMAAD4EAAAiAAAAAAAAAAAAAACAAQAAAABD',
  'b250YWluZXIvRG9jdW1lbnRzL2NvbWljQm9va3MuZGF0UEsBAhQAFAAAAAgA2iE7XWwEYIsCBwAAEgkAACQAAAAAAAAAAAAA',
  'AIABygMAAENvbnRhaW5lci9Eb2N1bWVudHMvY29taWNIaXN0cm95LmRhdFBLAQIUABQAAAAIANohO11Er9w1CgAAAAgAAAAv',
  'AAAAAAAAAAAAAACAAQ4LAABDb250YWluZXIvTGlicmFyeS9QcmVmZXJlbmNlcy9jb20uZXhhbXBsZS5wbGlzdFBLAQIUABQA',
  'AAAIANohO11Er9w1CgAAAAgAAAAUAAAAAAAAAAAAAACAAWULAABpVHVuZXNNZXRhZGF0YS5wbGlzdFBLBQYAAAAABAAEAEEB',
  'AAChCwAAAAA=',
].join('');

export const PLAIN = [
  'YnBsaXN0MDDbAQIDBAUGBwgJCgsMDQ4PEBUWFxgZGlVhc2NpaVNiaWdUZGF0YVNpbnRUbGlzdFhuZWdhdGl2ZVJub1RyZWFs',
  'V3VuaWNvZGVUd2hlblN5ZXNVcGxhaW4TAAABAAAAAABDAAECECqjERITEAFTdHdvoRQQAxP/////////+QgjQAQAAAAAAABp',
  'AUwAawBhAG0AaQAgIBQAIHL8M0HINJ5gAAAACQgfJSkuMjdAQ0hQVVlfaGxucnR4enyFho+iqwAAAAAAAAEBAAAAAAAAABsA',
  'AAAAAAAAAAAAAAAAAACs',
].join('');
